#!/bin/sh
alias ls='ls --color=auto'
alias la='ls -a'
alias nv=nvim
alias reb='shutdown -r now'
alias shut='shutdown -P now'
alias ..='cd ..'
alias ...='cd ../..'
alias ran='ranger'
alias lg='lazygit'
alias mkd='mkdir'
