#!/bin/sh
HISTSIZE=1000000
SAVEHIST=1000000
PATH=$PATH:~/.local/share/nvim/mason/bin/
MSYS=winsymlinks:nativestrict
export MANPAGER='nvim +Man!'
export MANWIDTH=999

export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="brave"

export QT_QPA_PLATFORMTHEME=qt5ct
