#!/bin/sh

export XDG_CURRENT_DESKTOP=Hyprland
export SDL_VIDEODRIVER=wayland
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=Hyprland
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_QPA_PLATFORM="wayland;xcb"
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export JAVA_AWT_WM_NONEREPARENTING=1
export CLUTTER_BACKEND="wayland"
export GTK_THEME=Adwaita-dark

exec Hyprland
