theme = "gruvbox"

[editor]
line-number = "relative"
cursorline = true
workspace-lsp-roots = ["cargo.toml", ".git"]
end-of-line-diagnostics = "hint"
indent-heuristic = "tree-sitter"

[editor.lsp]
display-inlay-hints = true

[editor.file-picker]
hidden = false
git-global = false

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.normal]
C-y = ":sh zellij run -n Yazi -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/picker.sh"
y = "yank_joined_to_clipboard"
p = ["paste_clipboard_after"]
P = ["replace_selections_with_clipboard"]
d = ["yank_joined_to_clipboard", "delete_selection"]
z = "move_next_word_start"
C-s = ":write"
"w" = "move_next_sub_word_start"
"b" = "move_prev_sub_word_start"
"e" = "move_next_sub_word_end"


[keys.select]
y = "yank_joined_to_clipboard"
p = ["replace_selections_with_clipboard"]
P = ["replace_selections_with_clipboard"]
d = ["yank_joined_to_clipboard", "delete_selection"]
c = ["trim_selections", "change_selection"]
"w" = "extend_next_sub_word_start"
"b" = "extend_prev_sub_word_start"
"e" = "extend_next_sub_word_end"

[keys.insert]
C-space = "completion"
